djangoapp2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('ankiety/', include('ankiety.urls')),
    # path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views

app_name = 'pizza'
urlpatterns = [
	path('', views.index, name='index'),
    path('skladnik/dodaj', views.SkladnikDodaj, name='skladnik_add'),
]

studenci/urls.py
from django.urls import path

from . import views
from django.views.generic import ListView
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
	path('', views.index, name='index'),
    path('miasta/lista', ListView.as_view(model=Miasto), name='miasta_lista'),
    path('miasta/', views.miasta, name='miasta'),
    path('miasta/dodaj', views.DodajMiasto.as_view(), name='miasta_dodaj'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasto.as_view(), name='miasta_edytuj'),
    path('miasta/usun/<int:pk>', views.UsunMiasto.as_view(), name='miasta_usun'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('uczelnie/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('login/', views.login, name='login'),
]

studenci/models.py
from django.db import models


class Miasto(models.Model):
    nazwa = models.CharField(
        verbose_name='miasto',
        max_length=30,
        help_text='Nazwa miasta')
    kod = models.CharField(
        max_length=6,
        help_text='Kod pocztowy')

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "miasta"

class Uczelnia(models.Model):
    nazwa = models.CharField(
        verbose_name='uczelnia',
        max_length=30,
        help_text='Nazwa uczelni')

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "uczelnie"

class Student(models.Model):
    imie = models.CharField('imię', max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField('rok studiów', max_length=3)
    dochod = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.imie + " " + self.nazwisko;

    class Meta:
        verbose_name_plural = "studenci"

studenci/forms.py
from django import forms

from studenci.models import Miasto


class StudentLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login:",
        max_length=25,
        widget=forms.TextInput()
    )


class UczelniaForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa uczelni:",
        max_length=30,
        widget=forms.TextInput()
    )

class MiastoForm(forms.Form):
    nazwa = forms.CharField(
        label="Nazwa uczelni:",
        max_length=30,
        widget=forms.TextInput()
    )
    kod = forms.CharField(
        label="Kod pocztowy:",
        max_length=6,
        widget=forms.TextInput()
    )


class MiastoModelForm(forms.ModelForm):
    class Meta:
        model = Miasto
        fields = ('nazwa', 'kod')

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from studenci.models import Miasto, Uczelnia
from studenci.forms import StudentLoginForm, UczelniaForm, MiastoForm, MiastoModelForm

from django.views.generic import ListView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

def index(request):
    # return HttpResponse("Witaj w aplikacji Studenci!")
    return render(request, 'studenci/index.html')


def miasta(request):
    if request.method == 'POST':
        form = MiastoForm(request.POST)
        # nazwa = request.POST.get('nazwa')
        # kod = request.POST.get('kod')
        # if len(nazwa.strip()):
        if form.is_valid():
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dane zapisano!")
            return redirect(reverse('studenci:miasta'))
        else:
            messages.error(request, "Błędne dane!")
    else:
        form = MiastoForm()

    miasta = Miasto.objects.all()
    kontekst = {
        'miasta': miasta,
        'form': form
    }

    return render(request, 'studenci/miasta.html', kontekst)


def uczelnie(request):

    if request.method == 'POST':
        form = UczelniaForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dane zapisano!")
            # przekierowanie
            return redirect(reverse('studenci:uczelnie'))
    else:
        form = UczelniaForm()

    uczelnie = Uczelnia.objects.all()
    kontekst = {
        'form': form,
        'uczelnie': uczelnie
    }

    if request.user.has_perm('studenci.add_uczelnia'):
        return render(request, 'studenci/uczelnie.html', kontekst)
    else:
        messages.info(request, "Nie możesz dodawać uczelni.")
        return redirect(reverse('studenci:index'))


def login(request):
    if request.method == 'POST':
        pass
    else:
        form = StudentLoginForm()

    kontekst = { 'form': form }
    return render(request, 'studenci/login.html', kontekst)


class ListaUczelni(ListView):
    model = Uczelnia
    context_object_name = 'uczelnie'
    template_name = 'studenci/lista_uczelni.html'


@method_decorator(login_required, name='dispatch')
class DodajMiasto(CreateView):
    model = Miasto
    fields = ('nazwa', 'kod')
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Dodano miasto!")
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class EdytujMiasto(SuccessMessageMixin, UpdateView):
    model = Miasto
    form_class = MiastoModelForm
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')
    success_message = 'Zaktualizowano miasto!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context


class UsunMiasto(DeleteView):
    model = Miasto
    success_url = reverse_lazy('studenci:miasta_lista')

studenci/templates/studenci/index.html
{% extends 'szablon.html' %}
{% block naglowek %}Studenci{% endblock naglowek %}

{% block tresc %}
    <p>Witaj wśród studentów!</p>
{% endblock tresc %}

studenci/templates/studenci/lista_uczelni.html
{% extends 'szablon.html' %}
{% block tytul %}Studenci – uczelnie{% endblock tytul %}

{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/login.html
{% extends 'szablon.html' %}
{% block naglowek %}Studenci – Logowanie{% endblock naglowek %}

{% block tresc %}

<form action="." method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>

{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Dodaj miasto</h2>

    {% if user.is_authenticated %}
        {% if perms.studenci.add_miasto %}
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Zapisz">
            </form>
        {% else %}
            <div class="well">Nie możesz dodawać miast!</div>
        {% endif %}
    {% endif %}

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto_confirm_delete.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Usuwanie miasta</h2>

    <form method="POST">
        <p class="lead">Czy rzeczywiście chcesz usunąć miasto:<br>
            {{ object.nazwa }}, {{ object.kod }}?
        </p>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Usuń">
    </form>

{% endblock tresc %}

studenci/templates/studenci/miasto_dodaj.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
    {% load crispy_forms_tags %}

<h2>Dodaj miasto</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Zapisz">
    </form>

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }} –
            <a href="{% url 'studenci:miasta_edytuj' miasto.id %}">
                Edytuj
            </a>
        </li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/miasto_list.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}

{% block tresc %}
<h2>Lista miast</h2>
<ol>
    {% for miasto in object_list %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }} –
            <a href="{% url 'studenci:miasta_edytuj' miasto.id %}">Edytuj</a>,
            <a href="{% url 'studenci:miasta_usun' miasto.id %}">Usuń</a>
        </li>
    {% endfor %}
</ol>
{% endblock tresc %}

studenci/templates/studenci/uczelnie.html
{% extends 'szablon.html' %}
{% block tytul %}Studenci – uczelnie{% endblock tytul %}

{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}
    {% load crispy_forms_tags %}
<h2>Dodaj uczelnię</h2>
<form action="." method="POST">
    {% csrf_token %}
    <!-- <input type="text" name="nazwa" maxlength="30">
    <br> -->
    {{ form|crispy }}
    <input type="submit" value="Zapisz">
</form>

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }}</li>
    {% endfor %}
</ol>
{% endblock tresc %}