ankiety/urls.py
from django.urls import path
from . import views

app_name = 'ankiety'
urlpatterns = [
	path('', views.ListaPytan.as_view(), name='lista-pytan'),
	path('pytanie/<int:pid>', views.pytanie_glosuj, name='pytanie-glosuj'),
]

djangoapp2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('ankiety/', include('ankiety.urls')),
    # path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views

app_name = 'pizza'
urlpatterns = [
	path('', views.index, name='index'),
    path('skladnik/dodaj', views.SkladnikDodaj, name='skladnik_add'),
]

ankiety/models.py
from django.db import models
from django.utils import timezone

class Kategoria(models.Model):
    nazwa = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'kategorie'

    def __str__(self):
        return self.nazwa


class Pytanie(models.Model):
    kategoria = models.ForeignKey(Kategoria, on_delete=models.SET_NULL,
                                  blank=True, null=True, related_name="pytania")
    tekst_pytania = models.CharField('tekst pytania', max_length=200)
    data_d = models.DateTimeField('data dodania', default=timezone.now)

    class Meta:
        verbose_name_plural = 'pytania'
        ordering = ['-data_d']

    def __str__(self):
        return self.tekst_pytania[0:50]


class Odpowiedz(models.Model):
    pytanie = models.ForeignKey(Pytanie, on_delete=models.CASCADE)
    tekst_odpowiedzi = models.CharField('tekst odpowiedzi', max_length=200)
    glosy = models.IntegerField('liczba głosów', default=0)

    class Meta:
        verbose_name_plural = 'odpowiedzi'

    def __str__(self):
        return self.tekst_odpowiedzi[0:50]

ankiety/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from ankiety.models import Pytanie, Odpowiedz
from django.shortcuts import get_object_or_404, redirect

class ListaPytan(ListView):
    model = Pytanie
    template_name = 'ankiety/lista_pytan.html'
    context_object_name = 'pytania'

    def get_queryset(self):
        return Pytanie.objects.order_by('-data_d')[:10]


def pytanie_glosuj(request, pid):
    pytanie = get_object_or_404(Pytanie, pk=pid)
    if request.method == 'POST':
        pass
    else:
        return render(request, 'ankiety/pytanie_glosuj.html', {'pytanie': pytanie})

ankiety/templates/ankiety/lista_pytan.html
{% extends 'szablon.html' %}
{% block tytul %}Lista Pytan{% endblock tytul %}

{% block naglowek %}Lista Pytań{% endblock naglowek %}
{% block tresc %}
    <ul>
    {% for p in pytania %}
        <li class="mb-1">
            <span class="lead">{{ p }}</span>
            <a href="{% url 'ankiety:pytanie-glosuj' p.id %}" class="btn btn-secondary btn-sm">Głosuj</a>
            <br>
        <span class="float-right">{{ p.kategoria.nazwa }}</span>
        </li>
    {% endfor %}
    </ul>
{% endblock tresc %}

ankiety/templates/ankiety/pytanie_glosuj.html
{% extends 'szablon.html' %}
{% block tytul %}Głosuj{% endblock tytul %}

{% block naglowek %}Głosuj{% endblock naglowek %}
{% block tresc %}
    <h3>{{ pytanie }}</h3>

    <form action="{% url 'ankiety:pytanie-glosuj' pytanie.id %}" method="post">
    {% csrf_token %}

    <ul class="list-unstyled">
    {% for o in pytanie.odpowiedz_set.all %}
        <li class="mb-1">
            <input type="radio" name="odpowiedz" id="o{{ forloop.counter }}" value="{{ o.id }}">
            <label for="o{{ forloop.counter }}">{{ o.tekst_odpowiedzi }}</label>
        </li>
    {% endfor %}
    </ul>

        <button type="submit" class="btn btn-secondary">Głosuj</button>
    </form>

{% endblock tresc %}